title: FENRIR
description: Real-Time Neuromorphic Processing of DVS Data on FPGA
theme: just-the-docs
math: mathjax

url: https://ponti17.github.io/fenrir/

aux_links:
  GitHub: https://github.com/ponti17/fenrir

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

callouts:
  highlight:
    color: blue
    opacity: 0.2
